import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";


const inter = Inter({
  variable: "--font-inter", 
  subsets: ["latin"],       
});
export const metadata: Metadata = {
  title: "Property Verifed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${inter.variable} antialiased`}
      >
        {children}
            <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
